fix the haproxy build error.
The haproxy building get a error.

/usr/bin/ld: /usr/local/lib//liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [haproxy] Error 1

Add a USE_DL=1 in build options and remove "-ldl" in LDFLAGS was fixed.